spring:
    application:
        name: pop

    config:
        import: optional:file:.env[.properties]
    datasource:
        url: ${DATABASE_URL}
#        username: ${DATABASE_USERNAME}
#        password: ${DATABASE_PASSWORD}
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    jpa:
        defer-datasource-initialization: true
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.SQLServerDialect
    sql:
        init:
            mode: always
            platform: mssql
#    cloud:
#        azure:
#            storage:
#                blob:
#                    connection-string: ${BLOB_URL}
#blob:
#    containerForImages: ${BLOB_IMG_CONT}
